### PR TITLE
Added polish translation of Chapters 1-4

### PR DESCRIPTION
**Pull request by katecpp**
Added polish translation of Chapters 1-4

### CODE REVIEW

**Comment by cojack** [comment]
👍

**Comment by jryannel** [comment]
Will you continue with the polish translation?

**Comment by jryannel** [comment]
Hi,

We might switch to a new way of translation using Transifex and PO files. So I would like to keep this open.

**Comment by jryannel** [comment]
Hi,

I just merged a larger change to restructure all chapters and use the online translation tool transifex. Please read https://github.com/qmlbook/qmlbook/blob/master/TRANSLATION.md. 

Translation is now done using a different system. Sorry for not being able to merge these changes. But I hope this will make the translation much smoother in the future. Cheers!

**Pull request closed without merging**
