### PR TITLE
Improve grammar, word choice, spelling, and idiomatic English - Chapters 1-7,15

### PR DESCRIPTION
**Pull request by RossRogers**
Hello Juergen and Johan,

Thank you for writing this tutorial.  I had been floundering, trying to get a grasp of QML, when I found your tutorial.  I have a much better understanding after reading chapters 1-4 of your tutorial.

As I went through the first four chapters, I took the liberty of improving the grammar, word choice, spelling, punctuation, and closeness to idiomatic English.  I am not a professional English editor, nor do I have a degree in anything like English, but I am a native speaker.

I haven't changed what you guys were saying, but I believe that others will find the text more readable if you accept this pull request.  I would like to continue editing the next chapters as I proceed through the tutorial, but I want to know if these edits will be merged or thrown away.

Thank you for the awesome tutorial you have created.  I believe you have definitely filled a need in the QML documentation ecosystem.

- Ross

### CODE REVIEW

**Comment by RossRogers** [comment]
@e8johan , @jryannel ,

I'd love to have you guys take a look at the edits.

**Comment by e8johan** [comment]
Hi Ross,

Thank you for your edits. They look great and we really appreciate your
help. We've both been a bit swamped at work lately, but I'll try to catch
up on this over the weekend!

Best regards,

Johan

**Comment by RossRogers** [comment]
Hey Johan ( @e8johan ),

Ping.  The edits are solid and I didn't change the content of you words. I bet your book will rise in English SEO due to the grammar fixes if you merge the pull request.

**Comment by e8johan** [comment]
This looks great! Thanks!

**Comment by RossRogers** [comment]
Thanks Johan.

**Pull request merged**
